import { Content, EquipmentItem, Qualification, Customer, CallState } from "./types";

export const DEFAULT_CONTENT: Content = {
  moodGood: "Wonderful! Great to hear that.",
  moodBad: "Oh, I'm sorry to hear that. Hopefully I can make your day a little better.",
  scriptSections: [
    {
      id: "greeting",
      title: "Greeting",
      body: "Thanks for holding, this is ________ with Smart Home Alarms. Who do I have the pleasure of speaking with?\n\nHow's your day going so far — good or bad?\n\n[MOOD LINE]\n\nYour call has been transferred over, I am one of the product specialists. My job is to get you more information — so I believe you are the homeowner?",
      note: "Ask the mood question, react with the mood line, then confirm homeownership right away.",
    },
    {
      id: "qualify",
      title: "Qualifying",
      body: "So currently, do you have a Home Security System or you don't?\n\nIF YES: It shows that you do not compromise on your home and life safety — but remember, thieves and risks have upgraded too. Our system gives you what older ones don't, so I will give you our top-of-the-line system, which will definitely meet your standards.\n→ So how long have you been using this system — is it 3 years, 4 years or longer?\n(If 3 years or longer, simply move on without verifying the contract.)\n\nIF NO SYSTEM: It's never too late to get your home protected. A home without security is just like leaving the door open. With our system, you'll get instant alerts, 24/7 protection, and complete peace of mind.\n\nIF SENIOR CITIZEN: Being a respected senior citizen, do you make all financial decisions yourself, or do you like to talk it over with someone in the family — like your son, daughter or a family member?",
      note: "ALL of this within 120 SECONDS — filter potential vs non-potential customers fast. Tick the answers in the left panel as you get them.",
    },
    {
      id: "internet",
      title: "Internet & Camera",
      body: "Now, let me ask you — do you have internet at your place?\n\nIF YES: That's wonderful! I am gonna help you get a camera on the outdoor. With our Smart HD camera, you can watch your home live, see exactly who's at your door, check on packages, even talk through the camera if needed. And it's all real-time — no delays, no guessing — and everything is stored securely in the cloud, so the evidence is safe. Sounds good?",
      note: "No internet → only CCTVs, monitor & Traditional plan. Mark it in the left panel.",
    },
    {
      id: "interactive",
      title: "Interactive Services",
      body: "Well, our system comes with Interactive Services which allows you and your family members to use your cell phones to arm and disarm the system from any part of the country you are.\n\nSo, do you use an iPhone or an Android phone?  — Wonderful!!!\n\nThen your home would be under your eyes 24/7, no matter wherever you are.",
      note: "No smartphone → can't install the app. Still qualifies for SP/Traditional.",
    },
    {
      id: "sensors",
      title: "Doors, Motion & Glass",
      body: "DOOR SENSORS → How many doors lead into the home from the outside?\n\nI am gonna get you sensors on your doors. And for the windows, I am gonna do Motion Detection inside the house — so if a bad guy tries to jump through a window, the system will get 'em.\n\nI am also gonna do Glass Breakage / Shock Detection in the home, so if an intruder tries to shatter the glass on a window and come in through, the alarm goes off as well.\n\nSo as soon as a burglar tries to mess with your door or a window, a loud, powerful siren goes off. The siren will scare them and the camera will capture everything.\n\nNow, do you have any question before I move on to the price?",
    },
    {
      id: "keyfob",
      title: "Key Fob",
      body: "You will also be getting a keychain remote to arm and disarm the system remotely.\n\nIt also has panic buttons — so if you or a family member has a sudden health issue, heart attack, fall, or a breathing problem, help is dispatched instantly with just one button. Alright?",
    },
    {
      id: "smoke",
      title: "Heat & Smoke Sensor",
      body: "You will be getting a 3-in-1 heat, smoke & freeze detector which will alert you and the authorities in case of any smoke or any fire activity inside of your home.",
      note: "Monitored smoke alarm also makes them eligible for a homeowner's insurance discount — good add-on line.",
    },
    {
      id: "panel",
      title: "Control Panel",
      body: "I'm gonna get you a 7-by-7-inch touchscreen panel that looks great in the home — just like an iPad hanging on the wall.\n\n1) This panel has a BUILT-IN CAMERA. Every time somebody touches that panel, it takes a snapshot of the person and sends it right to your phone. So even if you are not at home, you'll know who tried to touch the panel in your absence — was it an intruder or a family member.\n\n2) It comes with FACIAL RECOGNITION — walk in with your hands full of groceries and you don't have to fiddle with the panel. Just come in front of it and it disarms the system for you.\n\n3) It serves as a MINI-TV SCREEN. If you're inside without your cellphone on you, just go to the panel on the wall and see what's going on outside. You can even talk to the guy standing at your door, right on the panel. (Isn't that great?)",
      note: "TRADITIONAL: panel camera, facial recognition & voice communication are NOT included — they show red below when Traditional is selected.",
    },
    {
      id: "price",
      title: "Price",
      body: "Well, our regular price is $79 bucks a month — but let me see if I can apply any discount. So can I have your zip code?\n\nOkay, so you are in City ________ & State ________. OK, so let me see... you know, I already got a technician there within a 50-mile radius. So I can go ahead and get this price discounted to just $69.99 a month for you.\n\n[ LONG PAUSE — wait for customer response. If no response: \"Any question so far?\" ]",
      note: "Type the zip in the right panel first — then quote. Use the price table below the equipment list for the camera count you pitched.",
    },
    {
      id: "closing",
      title: "Closing & Appointment",
      body: "So here's how it works — our technicians are pretty thorough & professional. When he comes to your home, he will look at your house, get a real feel of it, and see what needs to go where.\n\nWhen everything checks out, he will go ahead & install it. It normally takes an hour to an hour & a half to install everything.\n\nEven after my technician is finished installing it, he'll remain there for you to make sure that you are comfortable using it. So you can ask him any question about the system.\n\nGREAT! So let me ask you — what time usually works best for you: morning, afternoon, or late afternoon?\n\nOK, surely — we can work around your schedule.",
    },
    {
      id: "info",
      title: "Customer Info",
      body: "So first things first — how do you spell your first and last name?\n\nWhat's your date of birth?\n\nWhat's the address for your home that we're protecting?\n\nWhat's your email address?\n\nWe always call you a day before we roll a truck to your home — so is this the best number to reach you at?\n\nIn case the alarm went off and we are not able to reach you, who would you like to list as your emergency contact? Like a family member or friend.\n\nHow would you rate your credit score — excellent, good, or fair?\n\nGreat! Let me give you a quick recap of the package we discussed, so when the tech does come out there are no surprises.",
      note: "Fill every field in the right panel as they answer. Credit score decides Smart Pay vs Traditional — set it in the left panel too.",
    },
    {
      id: "transfer",
      title: "Transfer",
      body: "Alright, so now let me bring one of my scheduling coordinators on the line for you. With the promotion going on, we have limited time slots, so let's see what they still have available for your area.\n\nNow everything looks great on my end. Hold on one moment, let me bring them on the line.\n\nWHEN VALIDATION PICKS UP (\"Hi, this is Chris\"):\n\"Hey Chris, I got a very good customer / Mr. John on the line with me. He is getting the system with 2 cameras at a discounted rate of $74.99 a month, along with the free installation. You can take over the call & you both have a good day.\"",
    },
  ],
  rebuttals: [
    {
      id: "dog",
      label: "I Have a Dog",
      icon: "dog",
      category: "objection",
      text: "I totally understand, and it's great that you have a dog — they can be a big deterrence. But unfortunately, most burglars know how to work around dogs. Some bring treats, some know how to avoid them entirely, and worst case, your dog could be harmed or locked away.\n\nThe system we're talking about is designed to protect both your home and your dog. The alarm instantly alerts you and the monitoring center even if you're not home. The cameras record everything in real time, so you can check on your dog and your property right from your phone.\n\nYour dog can bark, but our system can call for help, scare off intruders with a siren, and send emergency services immediately. Alright?",
    },
    {
      id: "what-do-i-get",
      label: "What Will I Get?",
      icon: "sensors",
      category: "objection",
      text: "Great question — let me keep it short and simple. You're getting the complete protection package:\n\n• Smart HD OUTDOOR CAMERA — watch your home live from your phone\n• 7\" TOUCHSCREEN PANEL — the brain of the system, right on your wall\n• DOOR SENSORS on every entry door\n• MOTION DETECTOR covering up to 2,500 sq ft\n• GLASS-BREAK DETECTION for the windows\n• KEYCHAIN REMOTE with a panic button\n• 3-in-1 HEAT, SMOKE & FREEZE detector\n• MOBILE APP — arm & disarm from anywhere\n\nAnd all of it is professionally monitored 24/7 — break-in, fire or medical, help gets dispatched instantly. Installation is completely free by our certified technician.\n\nSo now that you know what's included, let me get you the discounted price for your area. Alright?",
    },
    {
      id: "safe-area",
      label: "Safe Neighborhood",
      icon: "shield",
      category: "objection",
      text: "1) I completely understand, and it's great that you feel safe in your area. But security isn't just about crime — it's about being prepared for the unexpected. Our system also protects against fire, carbon monoxide, medical emergencies, and even break-ins when you're not home.\n\n2) I understand you live in a good neighborhood, but let's be honest — you can't rely on your neighbors to watch your home 24/7. They have their own lives, and even if they notice something, it's usually too late. With our smart cameras, you're not depending on anyone else — you see exactly what's happening around your home in real-time, anywhere you are, and get instant alerts the moment something's off. That's peace of mind your neighbors just can't give you.",
    },
    {
      id: "not-interested",
      label: "Not Interested",
      icon: "x",
      category: "objection",
      text: "1) I understand, and many people feel the same — until they realize most break-ins happen in areas people think are safe. Our advanced system combines a loud smart alarm with HD night-vision cameras, plus door sensors, window sensors, and glass-break detection, so you get instant phone alerts and intruders are stopped before they even enter.\n\n2) It's better to have protection before something happens, not after. Our advanced system gives you HD night-vision cameras, a powerful smart alarm, door and window sensors, and even glass-break detection — so you get instant phone alerts and intruders are scared away before they even get inside.",
    },
    {
      id: "cant-afford",
      label: "Can't Afford",
      icon: "wallet",
      category: "objection",
      text: "1) I completely understand — security is an investment and I respect you watching your budget. But in today's world, the cost of a break-in isn't just about money — it's the stress, the fear, and the loss of peace of mind. The system we're offering isn't just an alarm, it's a complete protection package with cameras, far more advanced than what most companies offer at double the cost. Because you qualify for our senior citizen promo, we're waiving installation and equipment fees and locking you in the lowest monitoring rate we've ever offered — something not available to everyone. It's an investment in your safety, your home, and your peace of mind. Let's secure your spot so you're protected starting today. Make sense?\n\n2) I completely understand — no one budgets for an alarm system until they need it. But by the time something happens, it's too late. This isn't just an alarm and camera system, it's a shield for your family and everything you've worked hard for. Other companies charge more for less, but right now you're getting it with zero installation, no equipment cost and the lowest lifetime monitoring rate. One break-in could cost you thousands. Let's secure this today, so every time you step out, you'll have the confidence your home is safe 24/7. Sound good?",
    },
    {
      id: "think-about-it",
      label: "Let Me Think",
      icon: "brain",
      category: "objection",
      text: "I completely understand — protecting your home is a big decision. But let me ask you honestly: what exactly do you feel you still need to think over? Is it the cost, or do you need time?\n\nIF PRICE: I get it — budget is important. But today you're getting our full system with HD cameras and the complete alarm system with free installation, locked in at the lowest monitoring rate we've ever offered. If you wait, you'll lose the promotion and end up paying a lot more later. That's exactly why most families lock it in while it's affordable. Let's secure today's deal before it's gone. Alright?\n\nIF TIME: I hear you — but honestly, burglars don't wait. Every day without protection is a risk. The good news is we can get you secured today with no upfront payment, and you start enjoying the peace of mind immediately. So do you want me to schedule the installation for tomorrow morning or afternoon?\n\nSTILL HESITATING: Let me ask you this — if something happened tonight, tomorrow, or even in the coming days, would you feel better knowing your family is already protected, or wishing you had acted sooner? Peace of mind is priceless, and that's exactly what we're locking in today. Alright?",
    },
    {
      id: "always-home",
      label: "Always At Home",
      icon: "home",
      category: "objection",
      text: "That's actually the best reason to have a system — because you're protecting the people inside the house, not just the house itself. Our system does much more than just stop burglars. It gives instant alerts in case of fire, gas leaks, or any forced entry. Even if someone tries to break in while you're at home, the alarm activates immediately, cameras record everything, and you can call for help in seconds. It's like having a 24/7 digital guard that never sleeps, never gets tired, and always protects your family. Sounds good?",
    },
    {
      id: "cops-45",
      label: "Cops Take 45 Min",
      icon: "police",
      category: "objection",
      text: "You're absolutely right — police response takes time sometimes. But here's the fact: the system isn't just about calling the cops, it's about protecting your family in those 45 minutes. The instant the alarm goes off, intruders know they've been detected, the loud siren scares them, and the camera captures everything. Most criminals run the moment they hear that alarm. And even if they don't, you have live video proof in your hands to act fast. So instead of waiting helplessly, you're in control right from the first second — and with the automated system and interactive services, you and your family members are connected to the system all the time.",
    },
    {
      id: "own-monitoring",
      label: "I'll Self-Monitor",
      icon: "eye",
      category: "objection",
      text: "I understand — checking your own cameras sounds like enough. But here's the thing: when an emergency happens, you might be asleep, busy, or away from your phone, and that delay could make all the difference. With 24/7 professional monitoring, the moment something happens, trained responders are already on it — dispatching police, fire, or paramedics within seconds.\n\nAs a security expert I believe: cameras give you eyes, but monitoring is the muscle that actually protects your home in real time. It means you don't have to constantly watch your phone — the system has your back every minute of the day.",
    },
    {
      id: "cheaper",
      label: "Cheaper Elsewhere",
      icon: "tag",
      category: "objection",
      text: "I completely understand, and it's true — you can always find cheaper systems. But when it comes to your family's safety, would you really want the cheapest, or the most reliable? What we're offering you today is the latest, state-of-the-art alarm system, ground-proven in thousands of homes to stop break-ins before they happen. You're not getting old stock or outdated models — you're getting state-of-the-art protection that most homeowners are upgrading to right now. Think of it like upgrading your phone: the old one might still work, but the latest model gives you speed, features, and security the old one never had.",
    },
    {
      id: "free-catch",
      label: "It's Free? / Catch?",
      icon: "gift",
      category: "objection",
      text: "I completely understand, and I wish I could say it's free — but here's the good part: our current promotion covers the most expensive part, the equipment and installation, so you're saving a huge amount compared to other companies. If you stay with me for just a minute, I'll customize a package that fits your home and budget, and you'll see why so many customers are jumping on this deal before it ends.",
    },
    {
      id: "email-me",
      label: "Email / Mail Me Info",
      icon: "mail",
      category: "objection",
      text: "PHONE VERSION: I completely understand you'd like something in writing, and normally I'd be happy to send it. Right now, because you qualify for our senior citizen program, we're waiving installation and locking in a special monitoring rate — but it's ending very soon. That's why we do things differently: we don't just sign you up over the phone. We send our certified technician to your home with all the equipment — he'll walk you through how it works, answer every question, and show you the paperwork. Once you see the full package, he'll install it right then and there, so you're protected the same day. Locking it in now ensures you get the full protection without paying more later.\n\nSHORT VERSION: Well, it's 2026 and by now everything has gone paperless. I'd recommend you go on our website and read more about it → 2GIG.com",
    },
    {
      id: "discount",
      label: "Any Discount?",
      icon: "percent",
      category: "objection",
      text: "I completely understand you're looking for the best deal — and the good news is we've already given you our special discounted rate. But what makes this package truly valuable is the extras you're getting at no cost: free tech support, full warranty on the equipment, free movers plan, and even up to 25% off your home insurance. So while I can't reduce the price any further, what I can promise is that you're getting far more value and long-term savings than what you're paying today. That's why most customers feel it's a smart investment rather than an expense. Alright?",
    },
    {
      id: "cancel-install",
      label: "Cancel On Install Day?",
      icon: "undo",
      category: "objection",
      text: "On the installation day, you're fully in control. Our technician will bring the same equipment as we promised you — you'll have the chance to match and verify everything before a single item is installed. If you see that you're not getting what we agreed on, you have every right to send our technician back. Once you're satisfied, you can then allow our tech to proceed with the installation. On top of that, every system comes with a warranty and 24/7 support, so you'll always be in a win-win situation.",
    },
    {
      id: "reuse-equip",
      label: "Reuse My Equipment?",
      icon: "recycle",
      category: "objection",
      text: "That's a great question, and I'm glad you asked. Reusing your existing equipment often can't match the encryption, speed, and security standards of today's technology. If something went wrong — like a break-in — it could put your safety and our reputation at risk. Our system is built with next-generation encryption and features designed to work seamlessly with our professional monitoring, so we can stand behind it 100% and guarantee you the protection and peace of mind you deserve.",
    },
    {
      id: "contract-length",
      label: "Contract? How Long?",
      icon: "file",
      category: "objection",
      text: "SOFT VERSION: It's not a contract — it's just a price agreement, not a complicated contract like other companies trap you in. That means the price we agree on today will never go up for as long as you're with us. Your home stays protected, your family stays safe, and your budget stays exactly where it is — no surprises, no hidden changes, ever.\n\nIF THEY PRESS (how long do I pay?): It's an industry-wide standard agreement for 36 months and it's the same with all the companies. This agreement ensures your price never goes up and you keep getting quality service.",
    },
    {
      id: "price-start",
      label: "Price? (Too Early)",
      icon: "dollar",
      category: "info",
      text: "That's a great question — I'm glad you asked. At our company we believe every home is different, so we like to customize the package for you. If you allow me a few more seconds, I'll tell you what's all included and what's the cost.",
    },
    {
      id: "has-system",
      label: "Already Has System",
      icon: "alarm",
      category: "info",
      text: "ASK: Is that just the basic security system, or you also got a camera?\n\n• Basic security system → pitch the CAMERA, and confirm they have internet.\n• Only got cameras → sell them on the MONITORED ALARM SYSTEM.\n\nGOOD FOLLOW-UP: \"Well, if I gave you a new system, what would you like to see in the new system?\" → Better equipment, better service, more cameras.",
    },
    {
      id: "upgrade-old",
      label: "Upgrade Old System",
      icon: "up",
      category: "info",
      text: "Security technology has changed a lot in the last few years — older systems are like flip phones: they work, but they can't do what a smartphone can. Our system uses artificial intelligence, can detect people vs. animals, and gives you instant video alerts. The moment someone tries to break in, our system instantly alerts the monitoring center, your phone, and even triggers the cameras to record the event in real time.",
    },
    {
      id: "four-cams",
      label: "Has 4+ Cameras",
      icon: "cams",
      category: "info",
      text: "ASK: Are these your own cameras, or were they installed by the alarm company?\n\n• Own cameras → use the \"Cheaper Elsewhere / upgrade\" rebuttal (state-of-the-art vs old stock).\n• From the alarm company → sell them on FEATURES: Military grade, wide angle, night vision, spotlight, video analytics.",
    },
    {
      id: "buyout",
      label: "< 6 Months On Contract",
      icon: "handshake",
      category: "info",
      text: "Well [customer name], we can surely help you out — buy out your contract and get you a new system. → Then explain the new system.\n\n(Only when their remaining contract is under 6 months. If they're still deep in their agreement — under ~2.6 years of use on a 36-month term — we can't offer anything.)",
    },
    {
      id: "all-windows",
      label: "Sensors On All Windows?",
      icon: "window",
      category: "info",
      text: "Well, as a security expert I don't recommend putting a sensor on every window — it's an old-school method. Over the years burglars have come to know how to bypass those sensors: they apply duct tape on the frame of the window, cut the glass and get inside the home, so the sensor on the frame remains undisturbed. I'd recommend a more advanced approach, which is motion detection and glass-breakage detection.",
    },
    {
      id: "one-motion",
      label: "1 Motion Sensor Enough?",
      icon: "motion",
      category: "info",
      text: "I get what you're saying — great question. The motion sensor we provide is designed to cover up to 2,500 square feet, which is more than enough to secure an entire average-sized home, not just one room. It uses wide-angle detection, so whether someone enters through the living room, hallway, or connected spaces, it instantly picks up movement. And here's the best part: we place this sensor right between your master bedroom and living room — the areas most people want to protect the most. One device works like a 24/7 digital guard, and if you ever want extra coverage, the system is fully expandable. Sounds good?\n\nBEDROOM WINDOW? → If someone breaks into the bedroom window, he won't just stay in the bedroom — he'll look for the valuables, and he will come across the motion sensor in the living room.",
    },
    {
      id: "garage",
      label: "Garage / Outbuilding",
      icon: "garage",
      category: "info",
      text: "ASK: How far is the shop/garage from your home — is it within the 100 ft area?\n\n• YES → We will put a motion sensor there, and the camera would be pointing towards it.\n• NO (farther than 100 ft) → \"Well, I cannot say anything for sure — let my technician come out, he will surely help you out.\"",
    },
    {
      id: "see-cameras",
      label: "Will You See My Cams?",
      icon: "privacy",
      category: "info",
      text: "Cameras are for your own eyes — we just monitor your home for break-ins, fires and medical emergencies. If there's a break-in we dispatch the police; if there's fire in the house, we dispatch the fire trucks; if you suffer a medical emergency, we call the ambulance for you. And you also get an alert on your phone — so if you're not at home, you still know what's going on.",
    },
    {
      id: "why-dob",
      label: "Why My DOB?",
      icon: "id",
      category: "info",
      text: "We only need to do a soft inquiry on your credit — we do not need your social or anything like that. All we need is your DOB, and it's not gonna affect your credit score.",
    },
    {
      id: "why-email",
      label: "Why My Email?",
      icon: "at",
      category: "info",
      text: "We're gonna set up an app on your phone, and for that we need your email. So what's your email address?",
    },
    {
      id: "credit-ask",
      label: "How To Ask Credit",
      icon: "credit",
      category: "info",
      text: "Since this is a special senior citizen promotion, we just need a rough idea of your credit score to confirm you qualify and lock in the free equipment and discounted monitoring rate. So how do you rate it — is it good, fair or excellent? Even an estimate is fine, it's just to confirm eligibility.",
    },
    {
      id: "medical",
      label: "Medical Features",
      icon: "medical",
      category: "rebuttal",
      text: "Our system comes with built-in medical alert features — meaning if you, a family member, or even a guest has a sudden health issue (heart attack, fall, breathing problem), help is dispatched instantly with just one button.\n\nMEDICAL PENDANT: goes around the neck or on your waist, water resistant. (Smart Pay only — NOT provided in Traditional.)",
    },
    {
      id: "smoke-alarm",
      label: "Smoke Alarm Pitch",
      icon: "fire",
      category: "rebuttal",
      text: "The smoke alarm I'm gonna get you is professionally monitored. It will instantly call the fire truck to your home, and also notifies you on your phone. So even if you are not at home, you still know what's going on.\n\nThe smoke alarms we all got in our homes are ordinary — they only give a beeping sound. If you're not home, you wouldn't know until your house is fully burned down.\n\nAnd just for having this monitored smoke alarm in your home, you're gonna be eligible for a discount on your homeowner's insurance.",
    },
    {
      id: "doorbell-swap",
      label: "Doorbell → Outdoor Cam",
      icon: "bell",
      category: "rebuttal",
      text: "ASK: Do you get much traffic at your door?\n\nIF NO: Alright, then I wouldn't recommend a doorbell cam — instead I'd recommend a camera that gives a broad view and also has 2-way audio on it. A doorbell cam only alerts if someone walks up to the door, whereas with this cam you can set up a virtual trip wire around your house — so if a car pulls up, you get notified right there.",
    },
    {
      id: "camera-pitch",
      label: "Camera Pitch",
      icon: "video",
      category: "rebuttal",
      text: "Our cameras aren't just there to show you a video — they're smart. They use artificial intelligence to tell the difference between a person, a car, or an animal. With our smart HD cameras, you can watch your home live, see exactly who's at your door, check on packages, even talk through the camera if needed. It's all real-time — no delays, no guessing. And everything is stored securely in the cloud, so even if someone tries to damage the camera, the evidence is safe.\n\nFEATURES: Military grade • Wide angle • Night vision • Spotlight • Video analytics • Virtual trip wire • Two-way audio • Weatherproof • Fully encrypted.",
    },
    {
      id: "short-lines",
      label: "Power One-Liners",
      icon: "bolt",
      category: "rebuttal",
      text: "• A break-in, fire, or medical emergency could cost thousands in damages — or even risk lives.\n• Our system protects you for less than a daily cup of coffee.\n• You're actually building ownership of the equipment — it's an investment, not an expense.\n• Older systems are like flip phones — they work, but they can't do what a smartphone can.\n• It's better to have protection before something happens, not after.\n• It's like having a guard on duty who never sleeps, never takes a day off.\n• You're not just getting an alarm system — you're getting complete safety, confidence, and peace of mind.\n• Think of it as a shield for everything you've worked hard for.\n• Our monitoring is like having emergency responders on standby, every single second.\n• Emergencies don't wait for you to notice. Our system never sleeps, never misses.",
    },
    {
      id: "open-questions",
      label: "Open-Ended Questions",
      icon: "question",
      category: "rebuttal",
      text: "• How do you currently keep your home safe when you're away?\n• What's the most important thing you'd like to protect in your home?\n• What's your biggest concern about home safety these days?\n• How important is video evidence to you in case something happens?\n• What changes have you noticed in your area over the years?\n\nACTIVE LISTENING: Good to hear • Wonderful • That makes sense • I hear you • I understand • Let me find that for you • Absolutely • Definitely • Certainly • I'd be happy to help.",
    },
  ],
};

export const EQUIPMENT: EquipmentItem[] = [
  {
    id: "camera",
    name: "Outdoor HD Camera",
    icon: "video",
    sp: true,
    traditional: true,
    pitch: "Smart HD, AI video analytics, virtual trip wire, night vision, spotlight, two-way audio, weatherproof, military grade, fully encrypted, cloud storage.",
    features: [{ text: "3rd & 4th camera (SP loan only — Traditional max 2)", sp: true, traditional: false }],
  },
  {
    id: "panel",
    name: "7\" Touchscreen Panel",
    icon: "panel",
    sp: true,
    traditional: true,
    pitch: "Like an iPad on the wall — controls the whole system.",
    features: [
      { text: "Built-in camera (snapshot to phone)", sp: true, traditional: false },
      { text: "Facial recognition disarm", sp: true, traditional: false },
      { text: "Voice communication / mini-TV talk", sp: true, traditional: false },
    ],
  },
  {
    id: "door",
    name: "Door Sensors",
    icon: "door",
    sp: true,
    traditional: true,
    pitch: "On every door leading in from outside — ask how many doors.",
  },
  {
    id: "motion",
    name: "Motion Detection",
    icon: "motion",
    sp: true,
    traditional: true,
    pitch: "Covers up to 2,500 sq ft, wide-angle — placed between master bedroom & living room.",
  },
  {
    id: "glass",
    name: "Glass-Break / Shock",
    icon: "glass",
    sp: true,
    traditional: true,
    pitch: "Alarm goes off if an intruder shatters window glass.",
  },
  {
    id: "keyfob",
    name: "Key Fob Remote",
    icon: "key",
    sp: true,
    traditional: true,
    pitch: "Stay / Away / Disarm + Panic button — help dispatched with one press.",
  },
  {
    id: "smoke",
    name: "3-in-1 Heat/Smoke/Freeze",
    icon: "fire",
    sp: true,
    traditional: true,
    pitch: "Professionally monitored — alerts you AND the authorities. Insurance discount.",
  },
  {
    id: "app",
    name: "Mobile App (Interactive)",
    icon: "phone",
    sp: true,
    traditional: true,
    pitch: "Arm/disarm from anywhere. Needs a smartphone + email.",
  },
  {
    id: "pendant",
    name: "Medical Pendant",
    icon: "medical",
    sp: true,
    traditional: false,
    pitch: "Around the neck or waist, water resistant — instant medical dispatch.",
  },
  {
    id: "garagedoor",
    name: "Garage Door Sensor",
    icon: "garage",
    sp: true,
    traditional: false,
    pitch: "Garage door protection — SP only.",
  },
  {
    id: "lock",
    name: "Smart Lock / Keyless Deadbolt",
    icon: "lock",
    sp: true,
    traditional: false,
    pitch: "Keyless entry deadbolt — smart digital add-on (+$5/mo, +$500 loan).",
  },
  {
    id: "thermostat",
    name: "Smart Thermostat",
    icon: "thermo",
    sp: true,
    traditional: false,
    pitch: "Smart digital add-on (+$5/mo, +$500 loan).",
  },
];

export const PRICE_TIERS = [
  { cams: 1, monthly: 69.99, monitoring: 24.99, equipment: 45, loan: 4000 },
  { cams: 2, monthly: 74.99, monitoring: 24.99, equipment: 50, loan: 4500 },
  { cams: 3, monthly: 79.99, monitoring: 24.99, equipment: 55, loan: 5000 },
  { cams: 4, monthly: 84.99, monitoring: 24.99, equipment: 60, loan: 5500 },
];

export const TRADITIONAL_RULES = {
  maxCameras: 2,
  extraCameraOneTime: 300,
  activationFee: 99.99,
  notes: [
    "Email verification is MANDATORY",
    "Credit score must be at least FAIR",
    "Activation fee $99.99 (NOT pitched)",
    "+1 camera → payment goes up by $300",
    "No medical pendant, no panel camera/facial/voice",
  ],
};

export const SP_RULES = {
  extraSmartMonthly: 5,
  extraSmartLoan: 500,
  notes: [
    "Credit score must be EXCELLENT or GOOD",
    "Loan applied: $4000–$5500 by camera count",
    "More cameras possible if customer is willing + excellent credit",
    "Smart lock / thermostat / garage door sensor available",
    "Each smart add-on: +$5/mo monitoring, +$500 loan",
  ],
};

export const DEFAULT_QUAL: Qualification = {
  homeType: "unknown",
  ownsHome: "unknown",
  ownsLand: "unknown",
  internet: "unknown",
  phone: "unknown",
  hasSystem: "unknown",
  systemAge: "unknown",
  buyoutLt6mo: "unknown",
  senior: "unknown",
  credit: "unknown",
};

export const DEFAULT_CUSTOMER: Customer = {
  firstName: "",
  lastName: "",
  email: "",
  zip: "",
  dob: "",
  address: "",
  bestNumber: "",
  emergencyContact: "",
};

export const DEFAULT_CALL: CallState = {
  mood: "unknown",
  qual: DEFAULT_QUAL,
  customer: DEFAULT_CUSTOMER,
  plan: "auto",
  cameras: 2,
  packageQty: {
    panel: 1,
    door: 2,
    motion: 1,
    glass: 1,
    keyfob: 1,
    smoke: 1,
    app: 1,
    pendant: 0,
    garagedoor: 0,
    lock: 0,
    thermostat: 0,
  },
  equipNotes: "",
  sectionIndex: 0,
  activeRebuttal: null,
  startedAt: null,
};
