"use client";

import { IconType } from "react-icons";
import {
  FaDog,
  FaShieldHalved,
  FaXmark,
  FaWallet,
  FaBrain,
  FaHouse,
  FaEye,
  FaTag,
  FaGift,
  FaEnvelope,
  FaPercent,
  FaRotateLeft,
  FaRecycle,
  FaFileContract,
  FaDollarSign,
  FaBell,
  FaArrowUp,
  FaVideo,
  FaHandshake,
  FaWindowMaximize,
  FaPersonWalking,
  FaWarehouse,
  FaUserShield,
  FaIdCard,
  FaAt,
  FaCreditCard,
  FaBriefcaseMedical,
  FaFire,
  FaBolt,
  FaCircleQuestion,
  FaDoorOpen,
  FaKey,
  FaMobileScreen,
  FaLock,
  FaTemperatureHalf,
  FaTabletScreenButton,
  FaWineGlass,
  FaBuildingShield,
} from "react-icons/fa6";
import { MdLocalPolice, MdSensors } from "react-icons/md";

const MAP: Record<string, IconType> = {
  dog: FaDog,
  shield: FaShieldHalved,
  x: FaXmark,
  wallet: FaWallet,
  brain: FaBrain,
  home: FaHouse,
  police: MdLocalPolice,
  eye: FaEye,
  tag: FaTag,
  gift: FaGift,
  mail: FaEnvelope,
  percent: FaPercent,
  undo: FaRotateLeft,
  recycle: FaRecycle,
  file: FaFileContract,
  dollar: FaDollarSign,
  alarm: FaBell,
  up: FaArrowUp,
  cams: FaVideo,
  handshake: FaHandshake,
  window: FaWindowMaximize,
  motion: FaPersonWalking,
  garage: FaWarehouse,
  privacy: FaUserShield,
  id: FaIdCard,
  at: FaAt,
  credit: FaCreditCard,
  medical: FaBriefcaseMedical,
  fire: FaFire,
  bolt: FaBolt,
  question: FaCircleQuestion,
  video: FaVideo,
  bell: FaBell,
  door: FaDoorOpen,
  key: FaKey,
  phone: FaMobileScreen,
  lock: FaLock,
  thermo: FaTemperatureHalf,
  panel: FaTabletScreenButton,
  glass: FaWineGlass,
  sensors: MdSensors,
  building: FaBuildingShield,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const C = MAP[name] ?? FaCircleQuestion;
  return <C className={className} />;
}
